### ISSUE TITLE
Syntax highlighting issue for record fields' documentation

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#102]
**Description:**
Consider the following source snippet and the documentation for the record fields are not properly highlighted.

<img width="621" alt="Screenshot 2021-06-25 at 15 05 37" src="https://user-images.githubusercontent.com/1329674/123405180-30457a80-d5c7-11eb-882b-5d895bea4971.png">

**Comment by prabushi** [comment]
This was fixed with https://github.com/wso2/ballerina-plugin-vscode/issues/81. 
@nadeeshaan 
Can you check if the mentioned highlighting issue exists for your scenario in the 2.1.0 release?

**Comment by nadeeshaan** [comment]
This is fixed in the latest release. Hence +1 to close.
