### ISSUE TITLE
The v2.1.0 plugin doesn't work on VSCode v1.56.2

### ISSUE THREAD

**Issue by MaryamZi** [wso2/ballerina-plugin-vscode#103]
**Description:**
$title, even though v2.0.0 did.

Installing from within VSCode seems to (silently?) fallback to 2.0.0.

Installing using the VSIX results in the following error.

```
Command 'Extensions: Install from VSIX...' resulted in an error (Unable to install extension 'wso2.ballerina' as it is not compatible with VS Code '1.56.2'.)
```

**Comment by prabushi** [comment]
This is probably because we have updated the supported vscode engine version to `1.57.0`.

**Comment by HirumalPriyashan** [comment]
We will need to update the required VSCode version to `1.67.0` to address recent changes and additions in the VSCode Notebook API.

**Comment by hevayo** [comment]
Outdated issue
