### ISSUE TITLE
Color the annotations

### ISSUE THREAD

**Issue by shafreenAnfar** [wso2/ballerina-plugin-vscode#125]
Consider the below code snippet.
<img width="939" alt="Screen Shot 2021-10-14 at 9 42 18 AM" src="https://user-images.githubusercontent.com/6178058/137431344-db8cf495-c7e8-41d3-b6e1-cc5013735778.png">

In this case, wouldn't it increase the code readability if we highlight @http:Payload annotation in some other color ? (maybe bright yellow).

**Comment by gigara** [comment]
This seems like an issue with the VSCode default theme (Light).

Light+
![Screenshot from 2022-01-07 18-10-43](https://user-images.githubusercontent.com/16335290/148545471-87abecd7-583e-44c5-b111-c69c50e9ff51.png)

Dark+
![Screenshot from 2022-01-07 18-05-23](https://user-images.githubusercontent.com/16335290/148545577-b22f6e12-a911-4c52-af62-22a998491fdb.png)


Light (Default Theme)
![Screenshot from 2022-01-07 18-09-09](https://user-images.githubusercontent.com/16335290/148545504-acb368fd-0966-42a7-a430-5e6e9b3e363c.png)
