### ISSUE TITLE
Plugin shows `Please sign in to Choreo to view performance predictions` message for each and every keystroke

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#127]
**Description:**
If we have a service, for each and every keystroke, the following info is shown, which is disrupting the user's flow.

Consider the following source capture as well,

https://user-images.githubusercontent.com/1329674/139789864-f73bf86e-a12a-46fe-b4a9-23bbd1f58560.mp4

**Comment by prabushi** [comment]
We can add an option such as 'Don't show this message' to the popup notification.

**Comment by nadeeshaan** [comment]
> We can add an option such as 'Don't show this message' to the popup notification so that the user can turn it off.

I think the problem here is that we are prompting this via an info message and even if we have/provide an option for the user to turn it off there is a chance of ignoring it. IMHO, 
1. In the first place this should not appear via `show message`. Even if we choose it, it should be a one time thing.
2. This kind of information is usually shown to the user through the status bar, as a permanent message/ error/ warning until user attend and resolve the issue. (Consider how windows office shows the activation expiration status)

Suggestions,
1. Utilise the status bar to show the error with a notifiable colour.
2. Use the message in combination with the status Bar item. We show the message one time, and then show the status through the status bar item.
