### ISSUE TITLE
Syntax Highlighting Issue with Check Expressions

### ISSUE THREAD

**Issue by sanjana** [wso2/ballerina-plugin-vscode#147]
**Description:**
The syntax highlighting doesn't work for the check expression in the following code segment (Line 6).
![image](https://user-images.githubusercontent.com/9464997/148357749-9bbb3cc2-3822-4552-b682-352a8d8d54ff.png)

**Steps to reproduce:**

```
import ballerina/io;
public function main() {
    json resp = check {LKR_USD: 0.004908};
        decimal rate;
        do {
	        rate = check resp.LKR_USD;
        } on fail var e {
            io:println(e);
        	rate = 0;
        }

        decimal r2 = rate*2;
        io:println(r2);
}

```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The syntax highlighting is overridden in here from the semantic highlighter.
![Screenshot from 2022-01-07 17-43-58](https://user-images.githubusercontent.com/16335290/148543598-4103d1a5-e8c4-4ec5-9892-560bdb26307a.png)
