### ISSUE TITLE
Diagram not loaded via diagram explorer for an http service

### ISSUE THREAD

**Issue by IMS94** [wso2/ballerina-plugin-vscode#149]
**Description:**
I have a simple CRUD service written in Ballerina. When I try to open the diagram view **via the diagram explorer**, it gives that **Oops...embarrassing** page.

Source code can be found at: https://github.com/IMS94/ballerina_examples/blob/master/crud_service

This is the page I'm getting:
![Screenshot from 2022-01-07 11-20-23](https://user-images.githubusercontent.com/11285165/148498372-083808e6-5ba9-40c6-8dc1-5a94a960a59a.png)

However, when I open the diagram side by side using the _Open Diagram View_ button on top right corner of the source view, low code editor gets loaded correctly.

**Steps to reproduce:**
See description. Clone the ballerina service I have pointed out and try the above steps.

**Affected Versions:**
Swan Lake GA Snapshot Build 1

**Suggested Labels (optional):**
Blocker?

**Comment by prabushi** [comment]
Moved.
