### ISSUE TITLE
Diagram generator and export support for VSCode

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#15]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Feb 11, 2019 at 06:51 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/36_

----

- [ ] A tool to generate the diagram (as a SVG) for a given ballerina program. 
- [ ] VSCode command/menu to export diagram for the current file

**Comment by prabushi** [comment]
Similar report https://github.com/wso2/ballerina-plugin-vscode/issues/26

**Comment by hevayo** [comment]
Closing due to being Outdated
