### ISSUE TITLE
Action menu is not fully visible.

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#150]
**Description:**
Please refer the following capture,

https://user-images.githubusercontent.com/1329674/148717623-4899a76f-d930-43f8-8dad-65b4dbf31c1c.mp4

**Steps to reproduce:**
Follow the action sequence of the screen capture

**Affected Versions:**
v3.0.0-preview-m6 at least

**Comment by hevayo** [comment]
Issue is fixed in the latest pluin
