### ISSUE TITLE
Shortcut key combination is not platform specific

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#152]
**Description:**
Consider the following capture, where the notification is not aware about the platform. For Mac OS, the key combination should be `Cmd + Z`
<img width="620" alt="Screenshot 2022-01-10 at 10 50 38" src="https://user-images.githubusercontent.com/1329674/148721441-157998c2-3526-4715-ba29-deab2a53fff3.png">

**Affected Versions:**
v3.0.0-preview-m6 at least

**Comment by prabushi** [comment]
@HirumalPriyashan will work on this.
