### ISSUE TITLE
Inconsistencies in type naming

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#156]
**Description:**
Consider the following screen capture.

https://user-images.githubusercontent.com/1329674/148875743-0662a34c-760a-49e6-81ed-967e20712b75.mp4

- Here, we have a duplicate variable name and hence the compiler identifies the type as `$CompilationError$` (semantic type).
- Now when we look at the diagram, it shows the particular erroneous semantic type.
- If we go to the variable editor form, now it shows the type according to the syntax tree information. 

If we maintain the syntax to diagram parity, shouldn't we show the syntax information on the diagram as well? Otherwise, in such erroneous scenarios, there is an inconsistency.

Also, check the following screen capture,

<img width="1282" alt="Screenshot 2022-01-11 at 09 23 05" src="https://user-images.githubusercontent.com/1329674/148878567-07236cf8-040e-423c-b452-5803b02b4fef.png">

Here, we have a user defined type definition which is in the same project and when showing in the diagram view, we show the fully qualified type name and that leads to a situation where the user cannot see the type name.

***Suggestions***
- Do not show the fully qualified type name
- If the type is defined in the same module, then show only the type definition name.
- If the type is coming from a module, use the module alias as defined in the source. 
   eg: `import ballerina/xyz;` => `xyz:TestType` => `xyz:TestType`  
         `import ballerina/xyz as alias;` => `xyz:TestType` => `alias:TestType` 

**Affected Versions:**
v3.0.0-preview-m7 at least

**Comment by prabushi** [comment]
This is fixed in the 3.0.0 extension release.

<img width="639" alt="Screenshot 2022-05-12 at 16 56 36" src="https://user-images.githubusercontent.com/5234623/168064462-b4a64bf7-7efe-463c-a6c9-a302a750cae9.png">
