### ISSUE TITLE
Invalid source generated by Diagram editor

### ISSUE THREAD

**Issue by malinthar** [wso2/ballerina-plugin-vscode#157]
**Description:**
Consider the following source code where I have a prefixed import statement for log module. When I use the diagram editor  to use the log:printInfo() function produces a invalid text edit as depicted in the following screen capture,  

![diagram editor](https://user-images.githubusercontent.com/35211477/148886024-ebdd50ab-21f0-4b4f-a2e8-7be263185c20.gif)

**Steps to reproduce:**

```Ballerina
import ballerina/log as log1;

configurable int port = 3000;


public function main() {
    log1:printInfo(port.toBalString());
}

```

**Affected Versions:**
plugin - Release v3.0.0-preview-m7
ballerina - 2201.0.0-SNAPSHOT

**Comment by hevayo** [comment]
Log was removed from the lowcode and now you need to add an expression from statement editor hence this issue is not valid
