### ISSUE TITLE
Diagram editor goes unresponsive

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#158]
**Description:**
Consider the following screen capture

https://user-images.githubusercontent.com/1329674/148892883-94835b51-7ca9-4772-a619-7833d29092c5.mp4

**Affected Versions:**
v3.0.0-preview-m7 at least

**Comment by prabushi** [comment]
We have removed the variable support inside the resource for now. Hence, the mentioned behavior is not available. We'll bring back resource variable support separately.
