### ISSUE TITLE
Highlighting breaks with qualified identifiers in a type definition

### ISSUE THREAD

**Issue by MaryamZi** [wso2/ballerina-plugin-vscode#163]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/time;

type Type int|time:TimeZone|time:Error;
```

![qualified_identifier_highlighting](https://user-images.githubusercontent.com/8376983/150278415-b4e5087a-9ceb-4495-9e2f-a110321693e1.png)

Note the module prefixes in the two qualified identifiers. 

**Affected Versions:**
2201.0.0-rc1

**Comment by prabushi** [comment]
`time` is picked up as a **storage.type** from the textMate grammar. But, it's overridden by semantic highlighting in the light+ theme.
<img width="640" alt="Screenshot 2022-01-20 at 10 55 14" src="https://user-images.githubusercontent.com/5234623/150278956-33d844c6-d153-4a1a-a10f-b16d0aafd769.png">
