### ISSUE TITLE
Bump versions of node modules automatically upon release

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#18]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Mar 26, 2019 at 10:20 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/37_

----

ATM we don't automatically update them. We need to plugin pre-release and post release hooks for maven release plugin. Furthermore we need to fix this along with gradle build.

**Comment by prabushi** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Jun 10, 2019 at 10:27 GMT_

----

we need to rethink how we can do this along with gradle release now. 

With https://github.com/ballerina-platform/ballerina-lang/blob/master/gradle/jsProject.gradle#L47, now versions of package.json files get updated. However, we should make it a part of release commit. Otherwise there will always be unstaged changes to them upon each build after a release, until someone commits.

**Comment by hevayo** [comment]
We have moved the build totally in to npm, closing the issue since this will be a planed task
