### ISSUE TITLE
Code before the workers are not showing in the Low-Code view in VS Code, including the workers

### ISSUE THREAD

**Issue by Nadeeshan96** [wso2/ballerina-plugin-vscode#186]
**Description:**

In Ballerina Low-Code view in VS Code, the code before the workers are not showing in the graphical view, including the workers.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/33286289/167107600-479a7094-25cd-4df0-a7cb-ec05428eaa96.png">

**Steps to reproduce:**
See this code.
```bal
import ballerina/io;

public function main() {

    future<int> futureResult0 = start foo();
    int|error unionResult0 = wait futureResult0;

    int a = 3;
    io:println("In function worker");

    worker A {
        io:println("In worker A");
    }

    @strand {
        thread: "any"
    }
    worker B {
        io:println("In worker B");
    }

    future<int> futureResult = start foo();
    int|error unionResult = wait futureResult;

    io:println("In function worker");
    int b = 3;
    io:println("function end");
}


function foo() returns int {
    return 4;
}
```
**Affected Versions:**
Plugin version: v3.0.0
Ballerina 2201.0.2 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
The fix is available in https://github.com/wso2/ballerina-plugin-vscode/releases/download/v3.0.1-preview-m18/ballerina.vsix

<img width="1620" alt="Screenshot 2022-05-12 at 12 04 22" src="https://user-images.githubusercontent.com/5234623/168006827-6a78032f-29f5-4081-8a6f-5333637a5aae.png">
