### ISSUE TITLE
Add support for running/creating Ballerina Tests in VSCode

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#2]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Wednesday Sep 12, 2018 at 08:31 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/43_

----

- [ ]  Run tests directly from VSCode editor 
- [x]  Generate tests for a particular function/service
- [ ] Show test results (figure out a way to properly show)

**Comment by prabushi** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Oct 23, 2018 at 05:58 GMT_

----

We are starting the work on running tests and displaying results. Test generation work is already in progress and @rasika is working on it.

**Comment by hevayo** [comment]
This is already available in the current VSCode plugin via VSCode test view.
