### ISSUE TITLE
[Data Mapper] Even after marking a field optional in the target type, data mapper still shows it as manadatory

### ISSUE THREAD

**Issue by wx-yz** [wso2/ballerina-plugin-vscode#236]
**Description:**
Even after marking a target field optional, data mapper UI still shows the field as mandatory

**Steps to reproduce:**
- Create source and target types
- Open data mapper, view source and mark attribute as optional

<img width="776" alt="Screenshot 2022-10-28 at 11 12 37 PM" src="https://user-images.githubusercontent.com/57770159/198799072-4355d73b-db45-479f-b9e2-7fe04147831c.png">

**Comment by ajanthasingam** [comment]
There is the difference between type being optional and field itself being optional.  In this case the type is being optional, which means ballerina expects it to have a mapping. (but the mapped value can be null) 
![Screenshot from 2022-11-03 15-19-24](https://user-images.githubusercontent.com/37667596/199690885-01e2fab0-5bfb-4335-952c-50a6287c690f.png)

To make the field itself optional, syntax is typeName fieldName?; (in this case 'string address?';). This works as expected in datamapper design view
