### ISSUE TITLE
[Data Mapper] Cannot map more than 2 source attributes to a target attribute

### ISSUE THREAD

**Issue by wx-yz** [wso2/ballerina-plugin-vscode#237]
**Description:**
When mapping more than 1 source attribute to a target attribute data mapper automatically concaternate the fields. However, if you try to map a third field it draws a line separate line and there's a spinning icon.

**Steps to reproduce:**
- Add a source type and a target type
- Load data mapper and map 2 source attributes to a single target attribute
- Then map the 3rd attribute, then data mapper will show a spinning icon

**Comment by kaje94** [comment]
Duplicate of https://github.com/wso2/ballerina-plugin-vscode/issues/230

**Comment by kaje94** [comment]
@wx-yz, The fix for this issue will be available with Ballerina VSCode plugin v3.3.3
