### ISSUE TITLE
[Data mapper] UI shows a valid transform function as invalid

### ISSUE THREAD

**Issue by wx-yz** [wso2/ballerina-plugin-vscode#239]
**Description:**
A transform function that's valid and no errors in the soruce view is visualzied as invalid in the UI
<img width="1277" alt="Screenshot 2022-10-28 at 11 45 49 PM" src="https://user-images.githubusercontent.com/57770159/198812466-6c471935-10a2-458a-a826-03a69d8dc5f9.png">

**Comment by madushajg** [comment]
@wx-yz This issue has been fixed and will be available in Ballerina VSCode plugin v3.3.3
