### ISSUE TITLE
Improving the terminology used in the Project Design tool

### ISSUE THREAD

**Issue by SumayyaZiyad** [wso2/ballerina-plugin-vscode#269]
**Description:**
This issue has been opened to discuss the $subject.

As of now, the following changes were suggested for the terms used.

- Project Design Tool ---> Application Architecture Tool
- Level 1 Service Diagram ---> Service Interaction Diagram
- Level 2 Service Diagram ---> Resource Interaction Diagram

The term type diagram was suggested to be left as it is.

@hevayo @sanjiva @sameerajayasoma @kaviththiranga @NipunaRanasinghe

**Comment by sanjiva** [comment]
I like the first two but not "Resource Interaction Diagram". Can we call it (say) "Service Interaction Diagram (Detailed)"?

**Comment by hevayo** [comment]
+1 for the "Service Interaction Diagram (Detailed)" 

And when we add these to the menu we can probably skip "Tool" and "Diagrams" ie. command could be "Ballerina: Application Architecture"
