### ISSUE TITLE
GraphQL service rendering

### ISSUE THREAD

**Issue by hevayo** [wso2/ballerina-plugin-vscode#273]
Currently GraphQL services are not specially treated in the diagram. What you see currently is that the GraphQL services are rendered in HTTP style. How can we improve on this and give a unique and better experience for GraphQL Services. 

GraphQL services will appear in diagram at two places. 
1. Service design view in the visual editor 
2. Application architecture view 

To test out we can use the GraphQL service written in Ballerina found [here](https://github.com/avinyafoundation/global-data/blob/main/api/main.bal)

**Comment by hevayo** [comment]
[GraphQL Voyager](https://ivangoncharov.github.io/graphql-voyager/) is a tool that allows you to visualize GraphQL service. You can try out above test service SDL attached here in the above tool [schema.graphql.txt](https://github.com/wso2/ballerina-plugin-vscode/files/9995059/schema.graphql.txt)

The tool would generate the following graph. You can also navigate the graph by clicking on paths and types. 

![Screenshot from 2022-11-12 19-04-32](https://user-images.githubusercontent.com/323846/201476557-91c3c712-c173-4f48-9fc0-68d6ce855e71.png)

**Comment by hevayo** [comment]
GraphQL service editing experience 
1. User will be given two tabs in the GraphQL design view 
    1. A graph like in GraphQL voyager will be given to edit visually
    2. A tab containing GraphQL SDL will be also given to edit 
2. In both of the above cases editing will directly modify the Ballerina code

**Comment by sachiniSam** [comment]
The GraphQL Designer view is available from Ballerina extension 4.0.0 onwards
