### ISSUE TITLE
Allow incorrect break points

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#29]
<a href="https://github.com/prabushi"><img src="https://avatars.githubusercontent.com/u/5234623?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prabushi](https://github.com/prabushi)**
_Monday Dec 21, 2020 at 10:08 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/119_

----

**Description:**
VSCode extension allow incorrect break points, including comments and method declaration level (This is not supported via the debug server). Have to mark invalid lines as **Unbound breakpoints**.

<img width="495" alt="Screenshot 2020-12-21 at 15 34 58" src="https://user-images.githubusercontent.com/5234623/102765275-6436ad80-43a2-11eb-936e-dad4fc4a8cd2.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hevayo** [comment]
This feature is released and the editor show the breakpoint validity when a debug session is started
