### ISSUE TITLE
Save diagram only have the components visible in viewport, not the full diagram

### ISSUE THREAD

**Issue by hevayo** [wso2/ballerina-plugin-vscode#296]
See the attached diagram generated from the export button in service interaction view. In it one of the endpoint is beyond the downloaded image. When you export an image you need to capture the full picture.

![project-diagram](https://user-images.githubusercontent.com/323846/201827532-a89e828c-8d4e-4fb7-93ae-bfb3ce4c657b.jpeg)

**Comment by SumayyaZiyad** [comment]
Closing this issue as the PR with the fix has been merged to the development branch.
