### ISSUE TITLE
Alignment issues in resource form

### ISSUE THREAD

**Issue by CharukaK** [wso2/ballerina-plugin-vscode#299]
**Description:**
$subject
<img width="610" alt="image" src="https://user-images.githubusercontent.com/18122888/201908220-c084db5c-4d34-4bf5-b4ab-4cf9b02e00e3.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by axewilledge** [comment]
This is also fixed in dev branch.
