### ISSUE TITLE
[Project Design Diagrams] Component model is incomplete when a package has more than one un-annotated service

### ISSUE THREAD

**Issue by SumayyaZiyad** [wso2/ballerina-plugin-vscode#306]
**Description:**
The service interaction diagrams are dependent on the user-defined `display` annotations to uniquely identify services. Hence, in the current FE implementation, the unannotated services are not displayed. 

To provide a more comprehensive picture, this behaviour is being improved to display all the services available in the workspace, regardless of whether they are annotated or not (difference would be that the interactions can be mapped in annotated services but not for unannotated services).

However, currently, the component models retrieved are incomplete when multiple services in the same package are unannotated. Since the `service ID` is an empty string for all unannotated services, all such unannotated services in a package update the same entry in the services map, leaving only one unannotated service entry per package .

**Comment by aneeshafedo** [comment]
To address this issue, shall we produce an UUID as the `serviceId` for unannotated services ? 
@NipunaRanasinghe @hevayo

**Comment by SumayyaZiyad** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38824
