### ISSUE TITLE
[Bug] Diagram expansion is not working correctly

### ISSUE THREAD

**Issue by kanushka** [wso2/ballerina-plugin-vscode#307]
**Description:**

Diagram function expansion is not working for the below scenario.

```ballerina
public function main() returns error? {
    var name = check getName();
}

function getName() returns string|error {
    return "xyz";
}
```
**Sample**

![image](https://user-images.githubusercontent.com/24244523/202692704-8e7849e5-7125-48b7-ba82-a2bcd132412a.png)

**Affected Versions:**
Dev

**Comment by hevayo** [comment]
Closing since the feature was discontinue
