### ISSUE TITLE
[Bug] Assigning an endpoint to the `var` type variable will break the diagram

### ISSUE THREAD

**Issue by kanushka** [wso2/ballerina-plugin-vscode#310]
**Description:**

Assigning an endpoint to the `var` type variable will break the diagram.

**Sample**

```ballerina
import ballerina/http;

public function main() returns error? {
    http:Client httpEp = check new (url = "");
    var newEp = httpEp;
}
```

![image](https://user-images.githubusercontent.com/24244523/202694267-c4e6c856-a27b-4ee4-9f26-5ca751f4ebf0.png)

**Affected Versions:**
Dev, Stage, Prod

**Suggested Solution**

**Comment by hevayo** [comment]
Fixed with 4.0.0
