### ISSUE TITLE
Extra link is created when adding intermediate clause in query expression

### ISSUE THREAD

**Issue by madushajg** [wso2/ballerina-plugin-vscode#325]
**Description:**
$Subject when the select clause expression is a primitive type
![2022-11-23 22 48 57](https://user-images.githubusercontent.com/26219651/203612939-f4207a73-26f8-40df-9261-23d4c5f8d5c5.gif)

**Steps to reproduce:**
Reproducible with the following source
```ballerina
type Person record {
    int id;
    string firstName;
    string lastName;
    int age;
    float[] lastWeights;
};

type Student record {
    string id;
    string fullName;
    int age;
    float[] weights;
};

function Person2Student(Person person) returns Student => {
    weights: from var lastWeightsItem in person.lastWeights
        where lastWeightsItem == 55.5
        select lastWeightsItem
};
```

**Affected Versions:**
v3.3.4-beta4

**Comment by kaje94** [comment]
This seems to be fixed now

![Screenshot from 2022-12-06 11-18-19](https://user-images.githubusercontent.com/20398722/205827678-556f48b3-c41a-447e-83ab-4de49ba008f6.png)
