### ISSUE TITLE
In data mapper, cannot select outer function call to add check expression

### ISSUE THREAD

**Issue by kaviththiranga** [wso2/ballerina-plugin-vscode#326]
**Description:**
I tried to use lang.int:fromString() to convert a string to int. Now I want add check expression for the entire expression but cannot select it in statement editor.

<img width="601" alt="Screenshot 2022-11-24 at 17 16 36" src="https://user-images.githubusercontent.com/1505855/203777215-9e9782b6-d0b3-4fe1-93be-0fc485129009.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaumini** [comment]
Statement editor now provides code actions to add check expressions

https://user-images.githubusercontent.com/36252572/216002066-185c0307-61c6-47ea-a2b1-c6459d122ca5.MOV

Fixed with https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/687
