### ISSUE TITLE
Cannot add a `request`, `caller` or `header` when adding a resource to a service

### ISSUE THREAD

**Issue by kanushka** [wso2/ballerina-plugin-vscode#328]
**Description:**

Cannot add a `request`, `caller` or `header` when adding a resource to a service.

**Steps to reproduce:**

1. Create a service using the low-code editor
2. Click the bottom plus button to add extra service
3. Click the `show` button on the Advance parameters
4. Click `Add Request`
5. Nothing happens

https://user-images.githubusercontent.com/24244523/203779076-5b05bc6d-6567-4f58-a5c4-b1c0aa5ca541.mp4

**Affected Versions:**
Dev

**Comment by tharindulak** [comment]
Closing this since it done.
