### ISSUE TITLE
Second level suggestions are not provided for library functions in statement-editor

### ISSUE THREAD

**Issue by sachiniSam** [wso2/ballerina-plugin-vscode#353]
**Description:**
No LS suggestions are shown when library function is selected. Ideally it should be suggesting the suggestions based on the dot operator

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/30947080/208166798-948180f2-bf1d-4208-ba95-9a1b694e44b3.png)

**Affected Versions:**
ballerina-plugin-vscode master branch
ballerina version - 2201.3.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaumini** [comment]
currently not reproducible

https://user-images.githubusercontent.com/36252572/208353544-5d538edd-92e3-4583-9732-ee1c067863f0.MOV
