### ISSUE TITLE
Cannot distinguish optional record fields in Data mapper inputs

### ISSUE THREAD

**Issue by madushajg** [wso2/ballerina-plugin-vscode#359]
**Description:**
$Subject
![Screenshot 2022-12-21 at 13 32 55](https://user-images.githubusercontent.com/26219651/208853718-7f2a3054-6e68-4007-9117-a91d57732264.png)

**Comment by kaje94** [comment]
This was fixed with https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/863
