### ISSUE TITLE
Data mapper - Unable to perform query actions for inner records

### ISSUE THREAD

**Issue by dhanushkasandakelum117** [wso2/ballerina-plugin-vscode#372]
In Data mapper we can do query selection for main records. However if we have records inside record then inner record query selections cant be performed using data mapper. There we have to use custom expression which is quite long and that transformation is not visible in the data mapper

For example lets take following record,
record {
        record {
            string? system;
            string value;
        }[] identifier;
        record {
            record {
                string system;
                string code;
                string display;
            }[] coding;
            string text;
        } code;
        record {
            string 'start;
        } period;
        record {
            string display;
        } issuer;
    }[] qualification;

So we can perform query selection on "qualification". However we cant perform data mapper query selection on "qualification -> identifier " or "qualification -> code -> identifier" since they are inner records.

I've tried a very long expressions to do this transformation, if anyone have better suggestions please let me know.
https://media.discordapp.net/attachments/1060432620648923188/1060432621273894972/Screenshot_51.png?width=1205&height=678

Check Discord link: https://discordapp.com/channels/957996897782616114/1060432620648923188/1060432620648923188

**Comment by madushajg** [comment]
As I understood, you are trying to map some inner array fields by using query expressions.  This is supported by recursive editing in DM as follows.

![2023-01-05 13 59 42](https://user-images.githubusercontent.com/26219651/211377769-b6647344-5f7c-4ac0-b6bc-2cf151048e3b.gif)

Please let us know if you have a different requirement.

**Comment by madushajg** [comment]
> As I understood, you are trying to map some inner array fields by using query expressions. This is supported by recursive editing in DM as follows.
> 
> ![2023-01-05 13 59 42](https://user-images.githubusercontent.com/26219651/211377769-b6647344-5f7c-4ac0-b6bc-2cf151048e3b.gif) [ ![2023-01-05 13 59 42](https://user-images.githubusercontent.com/26219651/211377769-b6647344-5f7c-4ac0-b6bc-2cf151048e3b.gif) ](https://user-images.githubusercontent.com/26219651/211377769-b6647344-5f7c-4ac0-b6bc-2cf151048e3b.gif) [ ](https://user-images.githubusercontent.com/26219651/211377769-b6647344-5f7c-4ac0-b6bc-2cf151048e3b.gif)
> 
> Please let us know if you have a different requirement.

@dhanushkasandakelum117 Does this solve your problem?

**Comment by madushajg** [comment]
Mapping via query expressions is also documented in https://wso2.com/ballerina/vscode/docs/visual-programming/data-mapper/#map-the-arrays
Closing this issue since this case is already supported. Please feel free to re-open the issue if the provided fix hasn't worked for you.
