### ISSUE TITLE
[Data Mapper] Invalid expressions can't be fixed

### ISSUE THREAD

**Issue by janihur** [wso2/ballerina-plugin-vscode#378]
**Description:**
One easily ends with expression where the expression structure is invalid but can't be fixed. See the attached screenshot for example where I find no way to remove faulty `.<add-expression>`. The best you can do is to use `undo` but it won't save you every time.

The workaround is to fix the problem in textual representation.

![data-mapper-4](https://user-images.githubusercontent.com/954293/211494287-1a25bbb8-858f-441c-9fa1-5838c978f826.png)

**Comment by madushajg** [comment]
Couldn't able to reproduce this on plugin v3.3.8 with Ballerina 2201.3.2. @janihur could you please specify your plugin version and bal version? Also it is great if there any specific steps/source that we can follow to reproduce this.

**Comment by janihur** [comment]
It looks like the plugin has been auto-updated and I can't anymore produce the same behaviour with plugin v3.3.8. I don't recall the version used weeks ago - it was the latest available when the issue has created.

**Comment by janihur** [comment]
Hmm ... I can still end to the same state. The editor is still pretty much useless.

Just try it out with string to integer mapping with somebody who doesn't know the tool inside-out and you'll figure it out too.

I don't have now the luxury to record a video about the problem. The video would explain everything in 15 seconds.

**Comment by madushajg** [comment]
Thanks a lot! We will work on a fix for this issue.

I would also like to introduce our [reference guide](https://wso2.com/ballerina/vscode/docs/references/statement-editor/statement-editor-overview/) about the Statement editor, which will give you a better understanding about the tool and it's capabilities.

Also, it would be great if you can point us some areas that we can focus on improving the editor :)
