### ISSUE TITLE
Data mapper - Root level close button

### ISSUE THREAD

**Issue by dhanushkasandakelum117** [wso2/ballerina-plugin-vscode#383]
This is regarding for suggesting an improvement. I was using healthcare records which are quite long (around 100 fields).
So by default data mapper show all the fields in the record expanded. This makes me kind of difficult to find the fields that are required, because i have to close all the expanded fields and find the field again. 

If data mapper not expand those fields by default(stay collapsed) or if it can integrate a button to close all the fields up to root level then the development will be easy.

Check out the discord link {Images are there}
https://discordapp.com/channels/957996897782616114/1062815200048324808/1062815200048324808

**Comment by madushajg** [comment]
This will be addressed via https://github.com/wso2/ballerina-plugin-vscode/issues/402. Hence closing the issue.
