### ISSUE TITLE
API Docs link in VSCode docs preview is not working after API docs revamp.

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/ballerina-plugin-vscode#434]
**Description:**

$subject. Seems it is caused by recent API docs revamp which resulted in URL change for API Docs.
It has the link - which is invalid : https://lib.ballerina.io/ballerina/sql/1.6.2/records/ExecutionResult
Correct link : https://lib.ballerina.io/ballerina/sql/1.6.2#ExecutionResult

E,g: 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/16300038/220736585-4795f22f-67c7-4411-a29f-2f0e7bc15380.png">

**Comment by malinthar** [comment]
The fix is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/39705
