### ISSUE TITLE
When the import is not available, service diagram is blank

### ISSUE THREAD

**Issue by kaumini** [wso2/ballerina-plugin-vscode#436]
**Description:**
When the import is not available for a service show an error

https://user-images.githubusercontent.com/36252572/220881975-f499cca1-3f2f-4690-ad3e-b9e336b9dea3.MOV

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Fixed with 4.0.0
