### ISSUE TITLE
Enable debugging specific test cases 

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#45]
<a href="https://github.com/prabushi"><img src="https://avatars.githubusercontent.com/u/5234623?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prabushi](https://github.com/prabushi)**
_Wednesday Apr 21, 2021 at 08:29 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/370_

----

**Description:**
Enable debugging specific test cases using the `bal test --tests <a list of testcase names> filePath` command. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/ballerina-platform/plugin-vscode/issues/150
https://github.com/ballerina-platform/plugin-vscode/issues/18

**Comment by prabushi** [comment]
<a href="https://github.com/prabushi"><img src="https://avatars.githubusercontent.com/u/5234623?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prabushi](https://github.com/prabushi)**
_Monday May 03, 2021 at 12:20 GMT_

----

Plugin related fix was added with https://github.com/ballerina-platform/plugin-vscode/pull/371/commits/db7bad37dbee299bb9a4c563a2e5422a90da53a2

**Comment by NipunaRanasinghe** [comment]
Closing since the debugging tests are already enabled with the recent changes.
