### ISSUE TITLE
[Improvement] RegExp template support under template expressions

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [wso2/ballerina-plugin-vscode#458]
**Description:**
$subject

**Describe your problem(s)**
![Screenshot 2023-04-06 at 10 42 46](https://user-images.githubusercontent.com/46857198/230281061-dad02b05-b538-4eb0-985a-44d3541fba75.png)

Support 
```
re `value`
```

**Comment by sachiniSam** [comment]
The requested changes are completed. therefore closing the issue
