### ISSUE TITLE
Diagram not generating on VS Code

### ISSUE THREAD

**Issue by shaniR** [wso2/ballerina-plugin-vscode#459]
**Description:**
Diagram is not getting generated for the following code 

import ballerinax/salesforce;
import ballerina/http;

function transform(ContactsInput contactsInput) returns ContactsOutput => {
    numberOfContacts: contactsInput.totalSize,
    contacts: from var recordsItem in contactsInput.records
        select {
            fullName: recordsItem.FirstName + recordsItem.LastName,
            phoneNumber: recordsItem.Phone,
            email: recordsItem.Email,
            id: recordsItem.Id
        }
};

type Attributes record {
    string 'type;
    string url;
};

type ContactsOutput record {
    int numberOfContacts;
    record {
        string fullName;
        string phoneNumber;
        string email;
        string id;
    }[] contacts;
};

type ContactsItem record {
    string fullName;
    string phoneNumber;
    string email;
    string id;
};

type ContactsOutput1 record {
    int numberOfContacts;
    ContactsItem[] contacts;
};

type RecordsItem record {
    Attributes attributes;
    string Id;
    string FirstName;
    string LastName;
    string Email;
    string Phone;
};

type ContactsInput record {
    int totalSize;
    boolean done;
    RecordsItem[] records;
};

# A service representing a network-accessible API
# bound to port `9090`.
service / on new http:Listener(9090) {

    # A resource for generating greetings
    # + name - the input string name
    # + return - string name with hello message or error
    resource function get greeting(string name) returns string|error {
        // Send a response back to the caller.
        if name is "" {
            return error("name should not be empty!");
        }
        return "Hello, " + name;
    }

# A resource for transforming contacts
# + contactsInput - the input contacts
# + return - transformed contacts or error
    resource function post contacts(@http:Payload ContactsInput contactsInput) returns ContactsOutput|error? {
        ContactsOutput contactsOutput = transform(contactsInput);
        return contactsOutput;
    }

}

**Steps to reproduce:**

**Affected Versions:**
Ballerina extension - 3.3.13
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shaniR** [comment]
Remove the salesforce import, and it worked. it's good if we can give an error message stating it.

**Comment by hevayo** [comment]
The diagram works in the above code with 4.0.0 but the datamapper fails to draw the lined inside the query segment when the code is not formatted 
![Uploading Screenshot from 2023-04-27 00-11-37.png…]()
