### ISSUE TITLE
Debugger asking for configurables even though they're provided in Config.toml

### ISSUE THREAD

**Issue by NipunaRanasinghe** [wso2/ballerina-plugin-vscode#463]
**Description:**
$subject. can we improve this default behaviour to pick values from Config.toml, when its provided?

<img width="1728" alt="debugger" src="https://user-images.githubusercontent.com/29032600/231340482-2b70a102-0501-4d51-a7be-ee21327d8037.png">

**Steps to reproduce:**
1. write a ballerina program having confiugurable variables
2. place Config.toml with required values
3. Run the debugger

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Closing the issue since config editor was disabled
