### ISSUE TITLE
Update Choreo console redirect pages with a unique design

### ISSUE THREAD

**Issue by kanushka** [wso2/ballerina-plugin-vscode#464]
**Description:**
Update Choreo console redirect pages with a unique design and messages.

**Existing pages**

Login with GitHub

![image](https://user-images.githubusercontent.com/24244523/232480167-170c55f2-f313-4395-8dd6-bc0b9359423b.png)

Configure GitHub repos

![image](https://user-images.githubusercontent.com/24244523/232480557-a062db50-4acc-4a0e-a170-3811735086d7.png)

![image](https://user-images.githubusercontent.com/24244523/232480627-e3b9f9aa-92f7-499d-8884-6e6b0704ae8b.png)

**Comment by hevayo** [comment]
Not relevant for the project
