### ISSUE TITLE
Help write Config.toml for applications

### ISSUE THREAD

**Issue by hevayo** [wso2/ballerina-plugin-vscode#486]
**Description:**
Currently if you run an application with mandatory configurable variables you will get an error saying configurable values are not provided. 

But the IDE can do better and create the Config.toml for the user

When user runs a program via IDE
1. User write an application with VSCode 
2. Click run from code-lens or other button in vscode
3. Check with LS if there are mandatory config values 
4. Check if there is a config file with mandatory configs
5. If no Config.toml inform user about the missing config 
6. Generate a Config.toml with the configuration fields 
7. Open Config.toml in VSCode as a new Tab

When editing Config.toml
1. Suggest possible config values with completion
2. Indicate missing mandatory config values via diagnostics

**Comment by axewilledge** [comment]
Scenarios to cover: https://docs.google.com/document/d/1tKEfsyyIhEQkFOoUt0_0PnlBRgkigJnoVG-G8IhNrPo/edit?usp=sharing

**Comment by axewilledge** [comment]
More options needs to be added
- [ ] Should be able to add optional config values which are not having a default values
