### ISSUE TITLE
Fast Run prints two "Stopped." lines 

### ISSUE THREAD

**Issue by hasithaa** [wso2/ballerina-plugin-vscode#512]
See attached image.

<img width="1136" alt="Screenshot 2023-06-27 at 09 50 39" src="https://github.com/wso2/ballerina-plugin-vscode/assets/1356214/77f4e397-8a45-4cd7-b207-366692d082a5">

Versions:
* Update 7 RC1
* https://github.com/wso2/ballerina-plugin-vscode/releases/tag/v4.3.123062609

**Comment by manuranga** [comment]
This was a planed changed since now two streams (stderror and stdout) are subscribed. Planing to hide one from the UI in next VSCode release.

**Comment by manuranga** [comment]
Part of https://github.com/ballerina-platform/ballerina-lang/issues/40704

**Comment by manuranga** [comment]
Fixed with https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/1666
