### ISSUE TITLE
Open ballerina samples in b.io with vscode

### ISSUE THREAD

**Issue by axewilledge** [wso2/ballerina-plugin-vscode#513]
**Description:**

Examples in ballerina.io currently have a link to the playground for the user to try them out. Currently there are many limitations in Ballerina Playground notably not being able to run services. As an alternative we can look at opening the sample in local VSCode with a single click so users can try the sample out easily. 

Phase 1 :  Open and run single files

Experience 
- User clicks on a link next to a sample
- For first users we will show a message requesting to install VSCode if not already installed 
- When click on the link we will open the sample in VSCode 
- If Ballerina plugin is not installed VSCode will prompt to install the plugin
- If Ballerina is not found Ballerina plugin will prompt to install Ballerina with a single click
- If all the requirements are there the file will be copied to Downloads directory and get opened in VSCode 
- User can click run in VSCode to execute the program

Things to consider,
- For security should we only allow to open samples publish by b.io ? 
- Samples needs to be stored in gists (Can use the existing samples)

Phase 2 : Open and run projects
- We can extend the above to git repositories

**Comment by axewilledge** [comment]
How to get the raw file:

https://gist.githubusercontent.com/ballerina-github-bot/74cea880fefcb463d26a0c46f38fce39/raw/hello_world.bal

**Comment by kaviththiranga** [comment]
Virtual Document - this can be used to open a file from a gist
https://code.visualstudio.com/api/extension-guides/virtual-documents

Virtual Workspace - can be used to open a whole repo as a workspace
https://code.visualstudio.com/api/extension-guides/virtual-workspaces

We should use the native way of loading remote files/folders in to workspace instead of manually downloading to a local dir

**Comment by axewilledge** [comment]
Got a concern for using the above Virtual methods as for example, virtual document/workspaces allow us to bring in remote files lazy loaded, but when editing the file, it expects to change the remote file - which is a problem for us. We want the user to download and edit/run freely

**Comment by axewilledge** [comment]
- Check how to preserve the URL after reloading the vscode once user downloads ballerina
- BBEs examples has the same as samples.  Should we open those?
- Concerns related to security when downloading files

**Comment by axewilledge** [comment]
We need to activate the ballerina side URI handlers to download the example file. At the moment the plugin activates only if the current opened vscode window is a ballerina project or the user runs a particular ballerina related command. Hence we need to active the plugin as soon as they installed the extension.

**Comment by axewilledge** [comment]
- Use temp directory to download the file
- For security verify the gist is coming from ballerina-platform

**Comment by axewilledge** [comment]
- Check if we can open a repository file without needing to create a gist
