### ISSUE TITLE
Invalid swagger is loaded when click on `try it` in a service

### ISSUE THREAD

**Issue by aneeshafedo** [wso2/ballerina-plugin-vscode#514]
**Description:**

When clicked on `try it` button which is on top of a service declaration, wrong swagger is getting loaded. It actually loads the swagger of another service in the same project. 

https://github.com/wso2/ballerina-plugin-vscode/assets/34091327/3e288ee8-8da5-45e7-99be-a14cb30ca7c1

**Steps to reproduce:**

**Affected Versions:**
2201.7.1 RC1 

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SumayyaZiyad** [comment]
This is because the service identifier was constructed incorrectly. Hence, the view was not able to identify the service and defaulted to the last available service in the package. This issue has been fixed and will be available with the next plugin patch release.
