### ISSUE TITLE
RC5 shows "Ballerina SDK: Detecting" forever

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#78]
<a href="https://github.com/jclark"><img src="https://avatars.githubusercontent.com/u/499966?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jclark](https://github.com/jclark)**
_Thursday May 27, 2021 at 08:40 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/398_

----

In Beta1 RC5 on Windows, VS Code shows "Ballerina SDK: Detecting" forever
<img width="926" alt="Screenshot 2021-05-27 153816" src="https://user-images.githubusercontent.com/499966/119794564-d5eec680-bf01-11eb-9b28-6abadd7d1524.png">

**Comment by prabushi** [comment]
<a href="https://github.com/prabushi"><img src="https://avatars.githubusercontent.com/u/5234623?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prabushi](https://github.com/prabushi)**
_Friday May 28, 2021 at 08:07 GMT_

----

@jclark Could you please check if you have another Ballerina extension installed in your VS Code? If so, uninstall the Ballerina extension that comes under `ballerina.ballerina` organization and keep the one that comes under `wso2.ballerina`. Apparently, it has picked up the older version first.

<img width="866" alt="Screenshot 2021-05-28 at 13 34 44" src="https://user-images.githubusercontent.com/5234623/119951631-c7fc7c80-bfb9-11eb-97fa-9d01ee3cefda.png">

**Comment by jclark** [comment]
Thanks. I removed the ballerina.ballerina extension, and the problem is fixed.
