### ISSUE TITLE
Currently opened file's diagnostics disappears when goto def is invoked on a stdlib or langlib construct

### ISSUE THREAD

**Issue by malinthar** [wso2/ballerina-plugin-vscode#84]
**Description:**
$subject captured as follows.

<img src="https://user-images.githubusercontent.com/35211477/120308108-5aba5580-c2f1-11eb-8bc6-922fd1d37334.gif" width=500 />

Since the file is closed current diagnostics disappears as well.

**Affected Product Version:**
slbeta1-rc6

**Steps to reproduce:**
Try above in VSCode

**Comment by prabushi** [comment]
Moved to https://github.com/ballerina-platform/ballerina-lang/issues/28168#issuecomment-852291532
