### ISSUE TITLE
Reload Window while debugging will not stop the current debug process

### ISSUE THREAD

**Issue by hasithaa** [wso2/ballerina-plugin-vscode#86]
Observed this behavior, while debugging a simple HTTP service in Windows. While debugging, I called `reload window` and try to debug again. This fails with the port already in use error.

**Comment by prabushi** [comment]
@NipunaRanasinghe Is there a way to kill the service's process if the debug stop request is not sent?

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe Is there a way to kill the service's process if the debug stop request is not sent?

@prabushi @hasithaa As it seems like the mentioned issue is not reproducible on Ubuntu or Mac, I suspect this could be a windows-specific issue. I will give a further update after debugging the debug server on windows.

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/wso2/ballerina-plugin-vscode/issues/86
