### ISSUE TITLE
[Question] While debugging, is it possible to dynamically highlight sequence diagram? (Originally from https://github.com/scheung38) 

### ISSUE THREAD

**Issue by NipunaRanasinghe** [wso2/ballerina-plugin-vscode#92]
**Description:**
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/23090

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hevayo** [comment]
We will not be implementing the above feature given the usage of sequence diagram will be more for documentation. But the sequence diagram will be used for tracing and monitering
