### ISSUE TITLE
Syntax highlighting issues for type names

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#98]
**Description:**
Consider the following screen capture, where the `R1` is not highlighted in line 21
<img width="718" alt="Screenshot 2021-06-21 at 15 41 07" src="https://user-images.githubusercontent.com/1329674/122746538-bb610080-d2a7-11eb-869a-b4af2b29379d.png">

**Comment by prabushi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31841
