### ISSUE TITLE
The record generated from 'Paste JSON as Record' is not relatively formatted

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#99]
**Description:**
The closing bracket of the final record is always added to the 1st column of the new line. Rather it should be formatted relative to the context.
![test-json](https://user-images.githubusercontent.com/5234623/122896331-97b0bf80-d366-11eb-8a58-be7b11480b5e.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hevayo** [comment]
Type definitions are allowed only at module level thus this is not a valid feature to have.
